# -*- coding: utf-8 -*-
"""Homework_2_МИСОБ_2026_Панина.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lg2MLvLzIpFEynKA1gYgzhxLxgw2LRTm

**Homework_2**

**Аналитика текста**

⚡️Дата публикации: 12 февраля 2026 г.
* ⏰ Срок сдачи без снижения: 23:59 MSK 1 марта 2026 г.
* ⏰ Крайний срок сдачи: 23:59 MSK 15 марта 2026 г.

После 23:59 MSK 1 марта 2026 г. оценка будет снижаться на 0,5 балла в день.
Работы, сданные после крайнего срока, приниматься не будут.

**Система оценивания**

Решение оценивается по 10-балльной шкале, где:
* **"9-10"** означает, что задание выполнено полностью, соблюдены все указанные требования по четырем частям.

* Работа выполнена аккуратно и точно, без существенных замечаний;

* Проведено дополнительное исследование и применены методы сегментации;

* Подготовлена ​​презентация с сопроводительным письмом.

* **"8"** — задание выполнено полностью, все четыре части домашнего задания выполнены:
* Проведен анализ данных, предоставлен рабочий код и таблицы для анализа данных;

* Представлены четкие выводы с подтверждающими данными (таблицы, графики).

* 80% заданий выполнено

* **"6-7"** — задание выполнено не полностью или имеет некоторые недостатки:
* Проведен анализ данных, предоставлен рабочий код и таблицы для анализа данных;

* Представлены четкие выводы с подтверждающими данными (таблицы, графики).

* 60% заданий выполнено

* **"4-5"** — задание выполнено со значительными недостатками:
* Проведен анализ данных, предоставлен рабочий код и таблицы для анализа данных;

* 40% заданий выполнено

* **"0-3"** — задание не решено или решено неправильно.

⚡️**Два идентичных или почти идентичных кода с выводами будут штрафоваться:
0 баллов обоим студентам за задание, независимо от их результатов.**

# **Задача**

## Часть 1: Анализ текста с помощью TF-IDF

Цель:

Изучить метод TF-IDF для векторизации текста
Сравнить различные подходы к векторизации
Провести статистический анализ текстовых данных

## Часть 2: Классификация тональности с помощью BERT

Задача:

Цель этой задачи — использовать предварительно обученную модель BERT для классификации тональности рецензий на фильмы.

## IMDB Dataset https://disk.yandex.ru/d/dhKpEgM4rQkLiQ;

# **Задание для части 1:**

**1. Рассчитайте метрику TF-IDF для любых трех песен на выбранном вами языке. (Вес задания: 30%)**

**2. Сравните TF-IDF с другими методами векторизации текста, такими как Count Vectorizer, Word2Vec или Doc2Vec. (Вес задания: 30%)**

**3. Проведите исследование, используя полученные преобразованные данные.
Какие слова/фразы встречаются чаще всего, а какие реже. (Вес задания: 20%)**

# **Задание для части 2:**

**4. Используйте предварительно обученную модель BERT для
классификации тональности отзывов о фильмах. (Вес задания: 20%)**

⚡️Все комментарии, описания сегментов и выводы по домашнему заданию можно вносить непосредственно в блокнот с кодом.

# **Описание задания**
**1. Рассчитайте метрику TF-IDF для любых трех песен на одном языке по вашему выбору. (Вес задачи: 30%)**

Исследование распределения данных:
* ✅ 1. Подготовка данных:
* Выберите 3 песни на одном языке
* Переработка текста:

* Преобразование в нижний регистр
* Удаление стоп-слов

* Лемматизация/стемминг
* Токенизация

* ✅ 2. Реализация TF-IDF:

* Использование

* sklearn.feature_extraction.text

* Расчет матрицы TF-IDF

* Визуализация результатов

Результаты части 1:
* ✅ Таблицы, сводные отчеты и графики (например, гистограммы и диаграммы «ящик с усами»);

* ✅ Все данные должны сопровождаться выводами, основанными на полученных результатах исследования (3-4 предложения);

* ✅ Данные подготовлены для сравнения с другими методами векторизации.

Снижение оценки:
* Слишком много таблиц и графиков без пояснений;

* Недостаточная очистка данных — стоп-слова не были удалены;

* Сводные таблицы и графики без сортировки;

**2. Сравните TF-IDF с другими методами векторизации текста, такими как Count Vectorizer, Word2Vec или Doc2Vec. (Вес задачи: 30%)**

⚡️Критерии сравнения:
* Вычислительная сложность
* Качество представления
* Интерпретируемость

Результат части 2:
* ✅ Было проведено сравнение трех методов векторизации в соответствии с указанными критериями сравнения;

Снижение оценки:
* Избыточное количество таблиц и графиков без пояснений;
* Реализовано менее трех методов;
* Не все критерии сравнения реализованы;

**3. Проведите исследование, используя полученные преобразованные данные. Какие слова/фразы встречаются чаще всего, а какие реже (вес задачи: 20%)**

Результаты части 3:
Выполнен статистический анализ текста;

* ✅ Выполнен статистический анализ текста;
* Отображение 10 наиболее часто встречающихся слов;
* Отображение 10 наиболее часто встречающихся сочетаний слов;
* ✅ Графическая визуализация (t-sne, WordCloud);

Выводы:
* Нет выводов относительно сравнения;
* Графики/таблицы не сравнивались;

**4. Используйте предварительно обученную модель BERT для
классификации тональности отзывов о фильмах. (Вес задачи: 20%)**


Execution algorithm::
* ✅ 1.Data preparation:
*   Loading IMDB Dataset https://disk.yandex.ru/d/dhKpEgM4rQkLiQ;
*   Text Preprocessing;
*   Train/Test Split;
* ✅ 2. Работа с BERT:
* Загрузите предварительно обученную модель BERT и соответствующий ей токенизатор с сайта Hugging Face:
* Hugging Face Transformers
* Токенизация
* Создание классификатора
* Подготовка данных: используйте токенизатор BERT для преобразования текстов в формат входных данных модели (входные идентификаторы, маски внимания и т. д.).

* ✅ 3. Обучение модели BERT:
* Тонкая настройка BERT: обучите модель на обучающем наборе данных и оцените ее качество на тестовом наборе данных;
* Оценка метрик:
* Точность
* Точность/Полнота
* F1-мера

Результаты части 4:
* ✅ Точность на тестовом наборе данных не ниже заданного порогового значения (например, 0,9).
* ✅ F1-мера для положительного класса близка к точности, что указывает на баланс между точностью и полнотой.
* ✅ Модель корректно различает явно положительные и явно отрицательные отзывы при ручной проверке примеров.
* ✅ Результаты стабильны при повторном разделении на обучающую и тестовую выборки (значительного снижения показателей не наблюдается).
* ✅ Время вывода на один отзыв достаточно короткое для практического использования (например, доли секунды на типичном GPU/CPU).
* ✅ Алгоритм обучения модели на основе задачи завершен;
* ✅ Все данные должны сопровождаться выводами, основанными на полученных результатах исследования (2-3 предложения);

Сниженная оценка:
* Модель не из Hugging Face / не BERT / не предварительно обучена;
* Отсутствует отдельная загрузка токенизатора или используется неправильный;
* Код существует, но не запускается из-за незначительных ошибок (импорт, имя модели);
* Тексты не токенизированы токенизатором BERT;
* Поля Input_ids и attention_mask (или аналогичные обязательные поля) не генерируются;
* Некорректные параметры токенизации (например, отсутствует заполнение/обрезка при необходимости);
* Отсутствует дополнительный линейный слой для бинарной классификации;
* Линейный слой присутствует, но количество выходов указано неверно / отсутствует активация на выходе при вычислении прогнозов;
* Модель вообще не обучалась;
* Отсутствует разделение между обучающим и тестовым наборами данных;
* Не выполняется расчет указанных метрик (точность, F1 или аналогичные);
* Метрики рассчитываются некорректно (например, на основе обучающих данных или из-за ошибки в коде);
* Код полностью идентичен примеру или работам других студентов.

# **Отправка результатов:**

* Отправьте домашнее задание через форму Яндекса в виде ссылки на ваш GitHub, где будут находиться все файлы и код (Python).
* GitHub должен быть открыт, а код должен работать без ошибок.
* Назовите репозиторий, используя шаблон (HW_2_2025-Имя_Фамилия).
* Ссылка на форму Яндекса: https://forms.yandex.ru/u/692f511f505690b43617e5a3

# **Дополнительные материалы для домашнего задания:**

* Пример анализа текстовых данных, обсуждавшийся на семинаре, как пример решения домашнего задания: https://colab.research.google.com/drive/1zD3NCuSORsg1BJEo5HSw7LtEzzMJ9nP4?usp=sharing;

* Анализ настроений с помощью обученного BERT (hugging face), обсуждавшийся на семинаре:
https://colab.research.google.com/drive/1vC8XoAeLRqBhth1aWTqmi9RlxDJP4Ol7?usp=sharing
* Пример описания исследовательской работы в формате презентации — шпаргалка для домашнего задания предоставлена ​​в папке с опциями: https://disk.yandex.ru/d/HK53_fe77k4rvA;


# GUI:
* https://desktop.github.com/
* https://git-scm.com/
* https://tortoisegit.org/

# Resources:
* * https://git-scm.com/book/ru/v2
* http://www-cs-students.stanford.edu/~blynn/gitmagic/intl/ru/
* https://guides.github.com/activities/hello-world/

Interactive tours: https://githowto.com/ru
* https://learngitbranching.js.org/?locale=ru_RU


# Useful links on each topic:
# **Занятие 4 Инструменты и методы текстовой аналитики**
* https://docs.google.com/presentation/d/1PY_JeAuRFdPkneEnpSaNAf6PYmO-waLABTHJcjvXEn0/edit?slide=id.g31d89f3c299_0_319#slide=id.g31d89f3c299_0_319

# **Занятие 5 Инструменты и методы текстовой аналитики**
* https://docs.google.com/presentation/d/1BOAZXyQAWgMoLQwcxDfIqYQB_BXNOsr5JQSzedk4G_g/edit?usp=sharing

# **List of literature**

* Converting text data and working with it in Python. URL:
    *    https://academy.yandex.ru/handbook/data-analysis/article/preobrazovanie-tekstovyh-dannyh-i-ra  bota-s-nimi-v-python

* Basics of Natural Language Processing for text. URL:  
    *   https://habr.com/ru/companies/Voximplant/articles/446738/

* The Natasha project. A set of high-quality open-source tools for natural Russian language processing (NLP). URL:
    *   https://habr.com/ru/articles/516098/

* Natasha Library. URL:
    *   https://natasha.github.io/

* Repository of a course on text analysis and natural language processing at the MIPT FIVT.  URL:
    *   https://github.com/andybelov/nlp_mipt

* Your guide to the world of NLP (Natural Language Processing). URL:  
    *   https://habr.com/ru/companies/otus/articles/705482/

* Introduction to Natural Language Processing. URL:
    *   https://stepik.org/course/1233/syllabus

* Morphological analyzer pymorphy2. URL:  
    *   https://pymorphy2.readthedocs.io/en/stable/

* Bolshakova E. I. AUTOMATIC TEXT PROCESSING IN NATURAL LANGUAGE AND COMPUTER LINGUISTICS. URL:    
    *   https://www.hse.ru/data/2012/04/05/1251263483/пособие%20школа%20по%20компьютерной%20linguistics%20 - %20 copy.pdf
* Let's create an Intelligent Chatbot. URL:  
    *   https://machinelearningmastery.ru/lets-build-an-intelligent-chatbot-7ea7f215ada6/

* The Illustrated BERT, ELMo, and co. URL:
    *   https://jalammar.github.io/illustrated-bert/

* BERT (языковая модель). URL:
    *   https://neerc.ifmo.ru/wiki/index.php?title=BERT_(языковая_модель)

* BERT, ELMO и Ко в картинках (как в NLP пришло трансферное обучение).    
    *   https://habr.com/ru/articles/487358/

* BERT for "Everyone" (Tutorial + Implementation). URL:
    *   https://www.kaggle.com/code/harshjain123/bert-for-everyone-tutorial-implementation

* Как использовать BERT для мультиклассовой классификации текста. URL:
    *   https://neurohive.io/ru/tutorial/bert-klassifikacya-teksta/

# **Pre-trained modules**
* Hugging Face, bert-base-uncased. URL:
    *   https://huggingface.co/bert-base-uncased

* BERT in DeepPavlov. URL:
    *   http://docs.deeppavlov.ai/en/master/features/models/bert.html
* BERT и Hugging face:
    *   https://colab.research.google.com/drive/1vC8XoAeLRqBhth1aWTqmi9RlxDJP4Ol7?usp=sharing

## Часть 1: Анализ текста с помощью TF-IDF

**Цель**: Изучить метод TF-IDF для векторизации текста
Сравнить различные подходы к векторизации
Провести статистический анализ текстовых данных

### **1. Рассчитайте метрику TF-IDF для любых трех песен на одном языке по вашему выбору. (Вес задачи: 30%)**

Исследование распределения данных:
* ✅ 1. Подготовка данных:
* Выберите 3 песни на одном языке
* Переработка текста:

* Преобразование в нижний регистр
* Удаление стоп-слов

* Лемматизация/стемминг
* Токенизация

* ✅ 2. Реализация TF-IDF:

* Использование

* sklearn.feature_extraction.text

* Расчет матрицы TF-IDF

* Визуализация результатов

Результаты части 1:
* ✅ Таблицы, сводные отчеты и графики (например, гистограммы и диаграммы «ящик с усами»);

* ✅ Все данные должны сопровождаться выводами, основанными на полученных результатах исследования (3-4 предложения);

* ✅ Данные подготовлены для сравнения с другими методами векторизации.

Снижение оценки:
* Слишком много таблиц и графиков без пояснений;

* Недостаточная очистка данных — стоп-слова не были удалены;

* Сводные таблицы и графики без сортировки;
"""

songs = {
    '7 цифр': {
        'filename': '7 цифр.mp3',
        'text': """
              В теле спрятана любовь
              Не верю ей, она давно ведёт свою игру
              Вместе — единый симптом
              Но есть ли, есть ли что-то после — не пойму

              И не зная, что потом
              Не зная, что потом, я опять бегу
              Не догоняя тот фантом
              В котором вместе мы, где тебя люблю

              7 цифр и звонок, 7 цифр и гудок
              Как мне найти любовь твою?
              Мелодия из семи нот
              Как мне найти любовь твою?
              В крови легальный яд, никто не виноват
              Между нами что-то есть, что-то есть
              7 цифр и звонок
              Дай мне найти любовь твою

              Запомни, но не вспоминай
              Безмолвно в глубинах взгляда память утопи
              Вечность, и мне не успеть
              Как прежде найти твоей любви немой ответ

              И не зная, что потом
              Не зная, что потом, я опять бегу
              Не догоняя тот фантом
              В котором вместе мы, где тебя люблю

              7 цифр и звонок, 7 цифр и гудок
              Как мне найти любовь твою?
              Мелодия из семи нот
              Как мне найти любовь твою?
              В крови легальный яд, никто не виноват
              Между нами что-то есть, что-то есть
              7 цифр и звонок
              Дай мне найти любовь твою

              Знаю, что ты будешь со мной, о-е
              Никто не сможет разлучить нас, о-о…
              7 цифр и звонок
              Как мне найти любовь твою?

              7 цифр и звонок, 7 цифр и гудок
              Как мне найти любовь твою?
              Мелодия из семи нот
              Как мне найти любовь твою?
              В крови легальный яд, никто не виноват
              Между нами что-то есть, что-то есть
              7 цифр и звонок
              Дай мне найти любовь твою
              """
    },
    'Так красиво': {
        'filename': 'Так красиво.mp3',
        'text': """
              Твоя любовь издавала звуки, похожие на шум океана.
              Твоя любовь подавала руки, чтобы залечивать ими раны.
              Твоя любовь прижимала к сердцу, так тихо-тихо и не отпускала.
              Твоя любовь возвращала в детство. Дарила всё, чего не хватало.

              Твоя любовь — это так красиво. Твоя любовь этих тактов сила.
              Твоя любовь лишь моё Светило. Твоя любовь — это так красиво.
              Твоя любовь — это так красиво. Твоя любовь этих тактов сила.
              Твоя любовь меня доводила, но твоя любовь — это так красиво.

              Твоя любовь — это так красиво. Твоя любовь этих тактов сила.
              Твоя любовь лишь моё Светило. Твоя любовь — это так красиво.
              Твоя любовь — это так красиво. Твоя любовь этих тактов сила.
              Твоя любовь меня доводила, но твоя любовь — это так красиво.

              Твоя любовь подпускала близко. Прощала крики, по нервам била.
              Прощала боль, признавала риски.Твоя любовь во мне всё мирила.
              Твоя любовь прикасаясь к телу. Меняла временно запах кожи.
              Твоя любовь становилась целым из двух частей, что так не похожи.

              Твоя любовь — это так красиво. Твоя любовь этих тактов сила.
              Твоя любовь лишь моё Светило. Твоя любовь — это так красиво.
              Твоя любовь — это так красиво. Твоя любовь этих тактов сила.
              Твоя любовь меня доводила, но твоя любовь — это так красиво.

              Твоя любовь — это так красиво. Твоя любовь этих тактов сила.
              Твоя любовь лишь моё Светило. Твоя любовь — это так красиво.
              Твоя любовь — это так красиво. Твоя любовь этих тактов сила.
              Твоя любовь меня доводила, но твоя любовь — это так красиво.

              Твоя любовь — это так красиво. Твоя любовь этих тактов сила.
              Твоя любовь меня доводила, но твоя любовь — это так красиво.
              Твоя любовь — это так красиво. Твоя любовь этих тактов сила.
              Твоя любовь лишь моё Светило. Твоя любовь меня доводила,
              Но твоя любовь — это так красиво.
              """
    },
    'Я не боюсь': {
        'filename': 'Я не боюсь.mp3',
        'text': """
              Твердили все: «Она не для тебя»,
              Но с каждым днём сильней влюблялся я.
              Не слыша никого, от взгляда твоего
              Куда-то подо мной плыла земля.

              С огнём играли, перешли черту
              Узоры наших тел и сердца стук.
              За острые края упали ты и я.
              Быть осторожным больше не хочу.

              Я не боюсь (я не боюсь).
              Я не боюсь (я не боюсь).
              В твой сладкий плен я сам сдаюсь.
              Осудит кто-то — ну и пусть.

              Я не боюсь (я не боюсь).
              Я не боюсь (я не боюсь).
              Узнать твою любовь на вкус,
              За гранью 18+

              Мне говорили: «Стой, не подходи!
              Она — опасность в высшей степени!»
              Но сердце сорвалось, и дрожью бьёт насквозь,
              Несёт на запредельной скорости.

              Я за тобой на край земли бегу.
              Сплошные полосы на части рву.
              В руках меня держи, ремнями привяжи,
              Быть осторожным больше не могу.

              Я не боюсь (я не боюсь).
              Я не боюсь (я не боюсь).
              В твой сладкий плен я сам сдаюсь.
              Осудит кто-то — ну и пусть.

              Я не боюсь (я не боюсь).
              Я не боюсь (я не боюсь).
              Узнать твою любовь на вкус,
              За гранью 18+

              Я не боюсь (я не боюсь).
              Я не боюсь (я не боюсь).
              В твой сладкий плен я сам сдаюсь.
              Осудит кто-то — ну и пусть.

              Я не боюсь (я не боюсь).
              Я не боюсь (я не боюсь).
              Узнать твою любовь на вкус,
              За гранью 18+
              """
    },
    'Идеальный мир': {
        'filename': 'Идеальный мир.mp3',
        'text': """
              Мы живём в идеально неправильном мире
              Сильных женщин и нежных мужчин.
              Тени лучших надежд застыли
              В кнопках 911.

              Иногда жизнь так хочется выпрямить,
              Стержнем быть для себя и для нас.
              Не бояться, что время бессмысленно;
              Не стесняться прерывистых фраз.

              Свет в глазах там, вдали зона риска.
              Мы чисты и сгораем, как искры.

              Моя реальность словно сто костров горит.
              Неидеальный идеальный мир.
              Я исправляю, как могу, а Бог простит —
              Мой идеальный мир.

              Мы стараемся чувствовать правильно,
              Дождь камней по полям соберём.
              Грустно плавимся воском без пламени,
              Но отчаянно тлеем и ждём.

              Лишь бы нас за успехи простили,
              Так, как сами себя не простим,
              В идеально задуманном мире
              Нежных женщин и сильных мужчин.

              Свет в глазах там, вдали зона риска.
              Мы чисты и сгораем, как искры.

              Моя реальность словно сто костров горит.
              Неидеальный идеальный мир.
              Я исправляю, как могу, а Бог простит —
              Мой идеальный мир.
              """
    }
}

"""#### Тут можно послушать песни :)"""

import os
from IPython.display import Audio, display

def play_song(song_name):
    filename = songs[song_name]['filename']
    if os.path.exists(filename):
        print(f"Файл найден: {filename}")
        display(Audio(filename, autoplay=False))
    else:
        print(f"Файл '{filename}' не найден в текущей папке!")
        print(f"Сначала скачайте песню '{song_name}'")
        print("\nДоступные MP3 файлы в папке:")
        found = False
        for file in os.listdir('.'):
            if file.endswith('.mp3'):
                print(f"{file}")
                found = True

print("Доступные песни:")
song_list = list(songs.keys())
for i, song_name in enumerate(song_list, 1):
    print(f"{i}. {song_name}")
try:
    choice = int(input("\nВведите номер песни (1-4): "))
    if 1 <= choice <= len(song_list):
        selected_song = song_list[choice-1]
        play_song(selected_song)
    else:
        print("Неверный номер!")
except ValueError:
    print("Введите число!")

!pip install pymorphy3

import re
import pymorphy3
from nltk.corpus import stopwords
import nltk
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import seaborn as sns
from sklearn.metrics.pairwise import cosine_similarity
from matplotlib.colors import LinearSegmentedColormap
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from sklearn.decomposition import PCA
import plotly.express as px

nltk.download('punkt')
nltk.download('stopwords')

def preprocess_russian_text(text, return_stats=False):
    """
    Функция для предобработки русскоязычного текста
    """

    morph = pymorphy3.MorphAnalyzer()

    russian_stopwords = set(stopwords.words("russian"))

    if return_stats:
        stats = {'initial_tokens': 0, 'after_stopwords': 0, 'after_lemmatization': 0}

    # Преобразование в нижний регистр
    text_lower = text.lower()

    # Удаление пунктуации и цифр
    text_clean = re.sub(r'[^\w\s]', ' ', text_lower)
    text_clean = re.sub(r'\d+', '', text_clean)
    text_clean = re.sub(r'\s+', ' ', text_clean).strip()

    # Токенизация
    tokens = text_clean.split()

    if return_stats:
        stats['initial_tokens'] = len(tokens)

    # Удаление стоп-слов и коротких слов
    tokens_no_stopwords = [token for token in tokens if token not in russian_stopwords and len(token) > 2]

    if return_stats:
        stats['after_stopwords'] = len(tokens_no_stopwords)

    # Лемматизация
    lemmatized_tokens = []

    for token in tokens_no_stopwords:
        try:
            parsed = morph.parse(token)[0]
            normal_form = parsed.normal_form
            lemmatized_tokens.append(normal_form)
        except:
            lemmatized_tokens.append(token)

    if return_stats:
        stats['after_lemmatization'] = len(lemmatized_tokens)
        stats['removed_percent'] = round((1 - len(lemmatized_tokens)/len(tokens)) * 100, 1)

    processed_text = ' '.join(lemmatized_tokens)

    if return_stats:
        return processed_text, stats
    else:
        return processed_text

def style_dataframe(df, gradient=False, num=0):
    """
    Функция для красивого отображения таблиц
    """

    header_color = '#2E7D32'
    index_color = '#2E7D32'
    hover_color = '#FFB74D'

    percent_cols = [col for col in df.columns if 'процентов' in str(col).lower() or '%' in str(col)]

    all_numeric = df.select_dtypes(include=[np.number]).columns.tolist()

    styles = [
        {'selector': 'thead th',
         'props': [('background-color', header_color), ('color', 'white'),
                   ('font-weight', 'bold'), ('text-align', 'center'), ('padding', '10px')]},
        {'selector': 'tbody th',
         'props': [('background-color', index_color), ('color', 'white'),
                   ('font-weight', 'bold'), ('text-align', 'left'), ('padding', '8px')]},
        {'selector': 'tbody td',
         'props': [('padding', '8px'), ('text-align', 'center'), ('font-size', '12px')]},
        {'selector': 'tbody tr:hover td, tbody tr:hover th',
         'props': [('background-color', hover_color), ('color', 'black'), ('transition', '0.2s')]}
    ]

    styled = df.style.set_table_styles(styles)

    format_dict = {}
    for col in all_numeric:
        if col in percent_cols:
            format_dict[col] = '{:.1f}%'
        else:
            format_dict[col] = f'{{:.{num}f}}'

    styled = styled.format(format_dict)

    if gradient and all_numeric:
        custom_cmap = LinearSegmentedColormap.from_list('custom', ['#FFF9C4', '#2E7D32'])
        styled = styled.background_gradient(cmap=custom_cmap, subset=all_numeric, axis=None)

    return styled

all_data = []
song_names = []

for song_name, song_info in songs.items():
    lyrics = song_info['text']
    processed_text, stats = preprocess_russian_text(lyrics, return_stats=True)
    all_data.append({
        'Исходные токены': stats['initial_tokens'],
        'После стоп-слов': stats['after_stopwords'],
        'После лемматизации': stats['after_lemmatization'],
        'Удалено процентов': stats['removed_percent'],
        'Обработанный текст': processed_text
    })
    song_names.append(song_name)

df_complete = pd.DataFrame(all_data, index=song_names)
style_dataframe(df_complete)

colors = ['#FF8E53', '#9B59B6', '#FFB347', '#4ECDC4', '#FF6B6B', '#45B7D1', '#96CEB4', '#3498DB', '#2ECC71', '#F1C40F']

song_names = df_complete.index.tolist()

fig, axes = plt.subplots(1, 2, figsize=(16, max(8, len(df_complete) * 0.3)))
fig.patch.set_facecolor('white')

ax1 = axes[0]
ax1.set_facecolor('white')

x = np.arange(len(df_complete))
width = 0.35

bars1 = ax1.bar(x - width/2, df_complete['Исходные токены'], width, label='До обработки', color=colors[4], edgecolor='white', linewidth=1, alpha=0.8)
bars2 = ax1.bar(x + width/2, df_complete['После лемматизации'], width, label='После обработки', color=colors[8], edgecolor='white', linewidth=1, alpha=0.8)
ax1.set_title('Сравнение объема текста до и после обработки', fontsize=14, fontweight='bold', pad=20)
ax1.set_ylabel('Количество слов', fontsize=12, fontweight='bold')
ax1.set_xticks(x)
ax1.set_xticklabels(song_names, rotation=45, ha='right', fontsize=10)  # ← ИСПРАВЛЕНО: используем song_names
ax1.legend(frameon=False, fontsize=11)
ax1.grid(True, axis='y', alpha=0.3, linestyle='--', linewidth=0.8, color='#aaaaaa')
ax1.set_axisbelow(True)
ax1.spines['top'].set_visible(False)
ax1.spines['right'].set_visible(False)
ax1.spines['left'].set_color('black')
ax1.spines['left'].set_linewidth(1.5)
ax1.spines['bottom'].set_color('black')
ax1.spines['bottom'].set_linewidth(1.5)

max_y = max(df_complete['Исходные токены'].max(), df_complete['После лемматизации'].max())
for bars in [bars1, bars2]:
    for bar in bars:
        height = bar.get_height()
        ax1.text(bar.get_x() + bar.get_width()/2., height + (max_y * 0.01),
                f'{int(height)}', ha='center', va='bottom', fontsize=8, fontweight='bold')

ax1.tick_params(axis='both', which='major', bottom=True, left=True, length=4, width=1, color='black')

ax2 = axes[1]
ax2.set_facecolor('white')
bar_colors = [colors[i % len(colors)] for i in range(len(df_complete))]
bars = ax2.barh(song_names, df_complete['Удалено процентов'], color=bar_colors, height=0.7, edgecolor='white', linewidth=1)
ax2.set_title('Процент слов, удаленных при обработке', fontsize=14, fontweight='bold', pad=20)
ax2.grid(True, axis='x', alpha=0.3, linestyle='--', linewidth=0.8, color='#aaaaaa')
ax2.set_axisbelow(True)
ax2.spines['top'].set_visible(False)
ax2.spines['right'].set_visible(False)
ax2.spines['left'].set_color('black')
ax2.spines['left'].set_linewidth(1.5)
ax2.spines['bottom'].set_color('black')
ax2.spines['bottom'].set_linewidth(1.5)

max_count = df_complete['Удалено процентов'].max()
for bar, count in zip(bars, df_complete['Удалено процентов']):
    x_pos = bar.get_width() + (max_count * 0.01)
    ax2.text(x_pos, bar.get_y() + bar.get_height()/2,
             f'{count:.1f}%', va='center', fontsize=9, fontweight='bold')

ax2.set_xlim(0, max_count * 1.15)
ax2.set_ylim(-0.5, len(df_complete) - 0.5)
ax2.tick_params(axis='both', which='major', bottom=True, left=True, length=4, width=1, color='black', labelsize=10)

plt.tight_layout()
plt.show()

"""Проведённая предобработка текстов (токенизация, лемматизация и удаление стоп-слов) существенно повлияла на объём анализируемых данных: в зависимости от песни было удалено от 17% до 50% слов. Наиболее интенсивной очистке подверглись песни 7 цифр и Я не боюсь — это говорит о том, что в их текстах присутствует большое количество служебных частей речи, местоимений и часто употребляемых слов, не несущих смысловой нагрузки."""

tfidf_vectorizer = TfidfVectorizer()

processed_texts = df_complete['Обработанный текст'].tolist()
songs = df_complete.index.tolist()

tfidf_matrix = tfidf_vectorizer.fit_transform(processed_texts)
feature_names = tfidf_vectorizer.get_feature_names_out()

tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=feature_names,
    index=songs
)

term_sums = tfidf_df.sum().sort_values(ascending=False)
tfidf_df_sorted = tfidf_df[term_sums.index]
style_dataframe(tfidf_df_sorted, gradient=True, num=3)

"""Главные слова песен:
1.  7 цифр: цифра, найти, любовь, твой, звонок
2.  Так красиво: любовь, твой, это, красиво
3.  Я не боюсь: бояться, твой
4.  Идеальный мир: мир, простить, идеальный

Анализ ключевых слов показал, что песни практически не пересекаются по уникальной лексике. Однако на этом фоне ярко выделяются слова твой и любовь, которые встречаются в 3 из 4 песен. Все тексты объединяет обращенность к кому-то и романтический подтекст.
"""

# Матрица косинусного сходства
similarity_matrix = cosine_similarity(tfidf_matrix)

similarity_df = pd.DataFrame(
    similarity_matrix,
    index=songs,
    columns=songs
)

plt.figure(figsize=(8, 6))
ax = sns.heatmap(similarity_df,
            annot=True, fmt='.2f', annot_kws={'fontweight': 'bold', 'fontsize': 12},
            cmap='RdYlGn', vmin=0, vmax=1, square=True, linewidths=1, linecolor='white',
            cbar_kws={'label': 'Косинусное сходство'})

plt.title('Матрица сходства песен', fontsize=14, fontweight='bold', pad=20)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""Песни практически не пересекаются

 - 7 цифр и Так красиво: сходство 0.35 — самое высокое среди всех пар
 - 7 цифр и Идеальный мир: сходство 0.10 — очень низкое
 - Так красиво и Идеальный мир: сходство 0.16 — низкое

Песни очень разные лексически — максимальное сходство всего 0.35, что говорит об уникальности каждой песни.
"""

term_sums = tfidf_df.sum().sort_values(ascending=False).head(10)
top_10_terms = term_sums.index.tolist()

fig = make_subplots(rows=1, cols=2, column_widths=[0.3, 0.7], subplot_titles=('Топ-10 терминов', 'Распределение по песням'))

for a in fig['layout']['annotations']: a['font'] = dict(size=14, family='Arial Black')

fig.add_trace(go.Bar(y=term_sums.index, x=term_sums.values, orientation='h',
    marker_color=colors, text=term_sums.values.round(3), textposition='outside',
    textfont=dict(size=11, family='Arial Black'), showlegend=False), row=1, col=1)

for i, term in enumerate(top_10_terms):
    songs_with = [s for j, s in enumerate(songs) if tfidf_df[term].values[j] > 0]
    values_with = [v for v in tfidf_df[term].values if v > 0]
    if songs_with:
        fig.add_trace(go.Bar(x=songs_with, y=values_with, name=term,
            marker_color=colors[i], text=[f'{v:.2f}' for v in values_with],
            textposition='outside', textfont=dict(size=10, family='Arial Black')), row=1, col=2)

fig.update_xaxes(title_text='<b>Суммарное TF-IDF</b>', range=[0, term_sums.max()*1.2], gridcolor='lightgray', griddash='dot', row=1, col=1)
fig.update_yaxes(title_text='<b>Термины</b>', gridcolor='lightgray', griddash='dot', row=1, col=1)
fig.update_xaxes(title_text='<b>Песни</b>', gridcolor='lightgray', griddash='dot', row=1, col=2)
fig.update_yaxes(title_text='<b>TF-IDF значение</b>', gridcolor='lightgray', griddash='dot', row=1, col=2)

fig.update_layout(title='Анализ важности терминов в песнях', title_x=0.5,
    title_font=dict(size=20, family='Arial Black'),
    plot_bgcolor='white', paper_bgcolor='white',
    legend=dict(x=1.02, y=1, font=dict(size=10, family='Arial Black')),
    height=500, width=1300, margin=dict(r=180))

fig.show()

colors = ['#FF6B6B', '#4ECDC4', '#45B7D1', '#96CEB4', '#FFE194', '#E6B89C', '#FE938C', '#9C89B8', '#B8F2E6', '#AFAF9C']

n_songs = len(songs)
n_cols = 2
n_rows = (n_songs + n_cols - 1) // n_cols

fig = make_subplots(
    rows=n_rows, cols=n_cols,
    subplot_titles=[song for song in songs],
    horizontal_spacing=0.15,
    vertical_spacing=0.2
)

for idx, song in enumerate(songs):
    row = idx // n_cols + 1
    col = idx % n_cols + 1

    # Получаем топ-10 терминов для текущей песни
    song_top_terms = tfidf_df.loc[song].sort_values(ascending=False).head(10)
    terms = song_top_terms.index.tolist()
    values = song_top_terms.values.tolist()

    fig.add_trace(
        go.Bar(y=terms, x=values, orientation='h', marker_color=colors[:len(terms)], text=[f'{v:.3f}' for v in values], textposition='outside', textfont=dict(size=10, family='Arial Black'), showlegend=False, name=song),
        row=row, col=col
    )

fig.update_layout(
    title='Топ-10 терминов по песням',
    title_x=0.5,
    title_font=dict(size=20, family='Arial Black'),
    plot_bgcolor='white',
    paper_bgcolor='white',
    height=400 * n_rows,
    width=1200,
    margin=dict(l=100, r=50, t=150, b=50)
)

for idx, song in enumerate(songs):
    row = idx // n_cols + 1
    col = idx % n_cols + 1

    song_top_terms = tfidf_df.loc[song].sort_values(ascending=False).head(10)
    max_value = song_top_terms.max()

    fig.update_xaxes(title_text='<b>TF-IDF значение</b>', range=[0, max_value * 1.2], gridcolor='lightgray', griddash='dot', row=row, col=col)
    fig.update_yaxes(title_text='<b>Термины</b>' if col == 1 else '', gridcolor='lightgray', griddash='dot', row=row, col=col)

fig.show()

"""**"7 цифр"**
 - Главная тема: Поиск и коммуникация
 - Ключевые термины: найти (0.471), цифра (0.429), звонок (0.3)
 - Технологические/коммуникационные термины сочетаются с романтикой (любовь - 0.3283)
 - Уникальные термины: цифра, звонок, кровь, нота

**"Так красиво"**
 - Главная тема: Эстетика и чувства
 - Ключевые термины: твой (0.552), любовь (0.552), красиво (0.353)
 - Самые высокие значения TF-IDF в паре твой/любовь (оба по 0.5523)
 - Уникальные термины: красиво, сила, доводить, светило

**"Я не боюсь"**
 - Главная тема: Преодоление страха
 - Ключевые термины: бояться (0.838), твой (0.198)
 - Абсолютный максимум по всем песням - бояться (0.838)
 - Уникальные термины: грань, плен, вкус, осудить, сладкий, сдаваться

**"Идеальный мир"**
 - Главная тема: Идеалы и прощение
 - Ключевые термины: мир (0.44), идеальный (0.294), простить (0.294)
 - Философские мотивы
 - Уникальные термины: идеальный, простить, гореть, бог, женщина, искра
"""

term_sums = tfidf_df.sum().sort_values(ascending=False)
categories = term_sums.head(10).index.tolist()
songs = df_complete.index.tolist()

fig = go.Figure()

for i, song in enumerate(songs):
    values = tfidf_df.loc[song, categories].values.copy()
    if values.max() > 0:
        values = values / values.max()
    values = values.tolist() + [values[0]]

    fig.add_trace(go.Scatterpolar(
        r=values, theta=categories + [categories[0]],
        fill='toself', name=song,
        line=dict(color=colors[i], width=3)
    ))

fig.update_layout(
    title=dict(
        text='<b>Нормализованное сравнение песен</b>', x=0.5,
        font=dict(size=20, family='Arial Black')
    ),
    polar=dict(
        radialaxis=dict(range=[0, 1.05], side='counterclockwise'),
        angularaxis=dict(tickfont=dict(size=11))
    ),
    width=900, height=600
)
fig.show()

"""1. любовь, твой, а так же это и красиво доминируют в песне Так красиво
2. цифра, найти и звонок - песня 7 цифр явно выделяется
3. бояться - песня Я не боюсь имеет максимальное значение
4. Идеальный мир доминирует по слову мир
"""

boxplot_data = []
for song in songs:
    for term in tfidf_df.columns:
        val = tfidf_df.loc[song, term]
        if val > 0:
            boxplot_data.append({
                'Песня': song,
                'TF-IDF': val,
                'Термин': term,
                'Термин (значение)': f'{term}: {val:.3f}'
            })

df_box = pd.DataFrame(boxplot_data)
fig = px.box(df_box, x='Песня', y='TF-IDF',
             color='Песня',
             color_discrete_sequence=colors[:len(songs)],
             title='Распределение TF-IDF значений по песням',
             points='outliers',
             hover_data={'Термин': True, 'TF-IDF': ':.3f'})

fig.update_layout(
    title=dict(text='<b>Распределение TF-IDF значений по песням</b>', x=0.5, font=dict(size=16, family='Arial Black')),
    xaxis_title='<b>Песни</b>',
    yaxis_title='<b>TF-IDF значение</b>',
    plot_bgcolor='white',
    paper_bgcolor='white',
    showlegend=False,
    width=1200, height=500
)

fig.show()

"""Анализ распределения TF-IDF:

1. **"7 цифр"**
- Медиана: 0.0429
- Особенность: Компактное распределение - большинство слов имеют схожую важность
- Текст сбалансирован, нет резкого доминирования одного термина
- Ключевой термин: 'найти' (0.4714)
2. **"Так красиво"**
- Медиана: 0.0177 (самое низкое значение)
- Очень компактное распределение - все слова имеют низкую важность
- Самый разнообразный текст с равномерным распределением слов
- Ключевые термины: 'твой' и 'любовь' (оба 0.5523)
3. **"Я не боюсь"**
- Медиана: 0.0443
- Широкий разброс от 0.03 до 0.8
- Контрастный текст - есть очень важные слова и много редких
- Ключевой термин: 'бояться' (0.8383) - абсолютный максимум
4. **"Идеальный мир"**
- Медиана: 0.0734 (самые высокие значения)
- Меньше всего выбросов, самое стабильное распределение
- Самая плотная лексика - много повторяющихся важных слов
- Ключевой термин: 'мир' (0.4403)

На основе проведённого TF-IDF анализа четырёх песен можно сделать вывод, что каждая из них обладает уникальной стилистической структурой: от контрастного текста с одним доминирующим словом (Я не боюсь) до равномерно распределённой лексики (Так красиво). Общей тематической линией выступают обращение (твой) и романтические мотивы (любовь), которые повторяются в большинстве песен. Статистические показатели (высокий эксцесс и правосторонняя асимметрия) подтверждают, что в каждом тексте есть несколько ключевых терминов, значительно выделяющихся на фоне остальных.

###**2. Сравните TF-IDF с другими методами векторизации текста, такими как Count Vectorizer, Word2Vec или Doc2Vec. (Вес задачи: 30%)**

⚡️Критерии сравнения:
* Вычислительная сложность
* Качество представления
* Интерпретируемость

Результат части 2:
* ✅ Было проведено сравнение трех методов векторизации в соответствии с указанными критериями сравнения;

Снижение оценки:
* Избыточное количество таблиц и графиков без пояснений;
* Реализовано менее трех методов;
* Не все критерии сравнения реализованы;
"""

!pip install gensim

import time
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from gensim.models import Doc2Vec, Word2Vec
from gensim.models.doc2vec import TaggedDocument
from sklearn.metrics.pairwise import cosine_similarity
import seaborn as sns
import nltk
nltk.download('punkt')

colors = ['#FF8E53', '#9B59B6', '#FFB347', '#4ECDC4', '#FF6B6B','#45B7D1', '#96CEB4', '#3498DB', '#2ECC71', '#F1C40F']

processed_texts = df_complete['Обработанный текст'].tolist()
songs = df_complete.index.tolist()

# Токенизация для Word2Vec
tokenized_texts = [text.split() for text in processed_texts]

# Подготовка для Doc2Vec
tagged_docs = [TaggedDocument(words=text, tags=[str(i)]) for i, text in enumerate(tokenized_texts)]

# TF-IDF
print("\nTF-IDF...")
start = time.time()
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(processed_texts)
tfidf_time = time.time() - start
print(f"Время: {tfidf_time:.4f} сек")
print(f"Размер: {tfidf_matrix.shape}")

# CountVectorizer
print("\nCountVectorizer...")
start = time.time()
count_vectorizer = CountVectorizer()
count_matrix = count_vectorizer.fit_transform(processed_texts)
count_time = time.time() - start
print(f"Время: {count_time:.4f} сек")
print(f"Размер: {count_matrix.shape}")

# 3. Word2Vec
print("\nWord2Vec...")
start = time.time()

word2vec_model = Word2Vec(sentences=tokenized_texts, vector_size=50, window=3, min_count=1, epochs=200, sg=1)

word2vec_vectors = []
for text in tokenized_texts:
    vectors = [word2vec_model.wv[word] for word in text if word in word2vec_model.wv]
    if vectors:
        word2vec_vectors.append(np.mean(vectors, axis=0))
    else:
        word2vec_vectors.append(np.zeros(word2vec_model.vector_size))
word2vec_vectors = np.array(word2vec_vectors)

word2vec_time = time.time() - start
print(f"Время: {word2vec_time:.4f} сек")
print(f"Размер: {word2vec_vectors.shape}")

# Doc2Vec
print("\nDoc2Vec...")
start = time.time()

doc2vec_model = Doc2Vec(vector_size=50, window=3, epochs=200, dm=0, min_count=1)
doc2vec_model.build_vocab(tagged_docs)
doc2vec_model.train(tagged_docs,total_examples=doc2vec_model.corpus_count, epochs=doc2vec_model.epochs)

# Получаем векторы документов
doc2vec_vectors = np.array([doc2vec_model.dv[str(i)] for i in range(len(processed_texts))])

doc2vec_time = time.time() - start
print(f"Время: {doc2vec_time:.4f} сек")
print(f"Размер: {doc2vec_vectors.shape}")

comparison_data = {
    'Метод': ['TF-IDF', 'CountVectorizer', 'Word2Vec', 'Doc2Vec'],
    'Время (сек)': [tfidf_time, count_time, word2vec_time, doc2vec_time],
    'Размерность': [tfidf_matrix.shape[1], count_matrix.shape[1],
                    word2vec_vectors.shape[1], doc2vec_vectors.shape[1]],
    'Тип': ['Взвешенная частота', 'Абсолютная частота', 'Эмбеддинги', 'Эмбеддинги'],
    'Интерпретируемость': ['Высокая', 'Высокая', 'Низкая', 'Низкая'],
    'Учет семантики': ['Нет', 'Нет', 'Да', 'Да']
}

df_comparison = pd.DataFrame(comparison_data)
style_dataframe(df_comparison, gradient=True, num=4)

"""По вычислительной сложности CountVectorizer и TF-IDF работают значительно быстрее (0.01-0.02 сек) по сравнению с Word2Vec и Doc2Vec (0.9-1.5 сек), что делает их предпочтительными для задач, где важна скорость обработки. По качеству представления на малом объеме данных (4 документа) эмбеддинги не могут обучиться должным образом и показывают низкую эффективность, в то время как частотные методы адекватно отражают содержание текстов. По интерпретируемости TF-IDF и CountVectorizer выигрывают, так как каждый признак соответствует конкретному слову. Таким образом, для данного набора данных оптимальным выбором являются TF-IDF или CountVectorizer."""

fig, axes = plt.subplots(2, 2, figsize=(14, 12))
fig.patch.set_facecolor('white')

matrices = {
    'TF-IDF': tfidf_matrix,
    'CountVectorizer': count_matrix,
    'Word2Vec': word2vec_vectors,
    'Doc2Vec': doc2vec_vectors
}

titles = ['TF-IDF: матрица сходства', 'CountVectorizer: матрица сходства', 'Word2Vec: матрица сходства', 'Doc2Vec: матрица сходства']

for idx, (method, title) in enumerate(zip(matrices.keys(), titles)):
    ax = axes[idx // 2, idx % 2]
    ax.set_facecolor('white')

    matrix = matrices[method]

    if method in ['Word2Vec', 'Doc2Vec']:
        norms = np.linalg.norm(matrix, axis=1, keepdims=True)
        norms[norms == 0] = 1
        matrix_norm = matrix / norms
        sim_matrix = cosine_similarity(matrix_norm)
    else:
        sim_matrix = cosine_similarity(matrix)

    sim_df = pd.DataFrame(sim_matrix, index=songs, columns=songs)

    # Тепловая карта
    sns.heatmap(sim_df, annot=True, fmt='.2f', annot_kws={'fontweight': 'bold', 'fontsize': 10},
                cmap='RdYlGn', vmin=0, vmax=1, square=True, linewidths=1, linecolor='white',
                cbar=True, ax=ax, cbar_kws={'label': 'Сходство', 'shrink': 0.8})

    ax.set_title(title, fontsize=13, fontweight='bold', pad=10)
    ax.set_xticklabels(songs, rotation=45, ha='right', fontsize=9)
    ax.set_yticklabels(songs, fontsize=9)

plt.tight_layout()
plt.show()

"""Анализ матриц сходства показывает существенные различия между методами векторизации. Частотные методы (TF-IDF и CountVectorizer) демонстрируют более реалистичную картину с широким диапазоном значений сходства и низким средним сходством, что правильно отражает разнородность текстов песен — например, полное отсутствие сходства между 7 цифр и Идеальный мир. Word2Vec показывает высокое среднее сходство (0.651) и завышенные значения даже для разных песен (0.415 между 7 цифр и Идеальный мир), что свидетельствует о неспособности модели качественно обучиться на малом количестве документов. Doc2Vec занимает промежуточное положение со средним сходством 0.482, но также склонен к завышению оценок, подтверждая, что для эмбеддингов требуется значительно больше обучающих данных для представления семантики текстов.

###**3. Проведите исследование, используя полученные преобразованные данные. Какие слова/фразы встречаются чаще всего, а какие реже (вес задачи: 20%)**

Результаты части 3:
Выполнен статистический анализ текста;

* Выполнен статистический анализ текста;
* Отображение 10 наиболее часто встречающихся слов;
* Отображение 10 наиболее часто встречающихся сочетаний слов;
* Графическая визуализация (t-sne, WordCloud);

Выводы:
* Нет выводов относительно сравнения;
* Графики/таблицы не сравнивались;
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from wordcloud import WordCloud
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.manifold import TSNE
import seaborn as sns
from collections import Counter

# Топ-10 слов
all_words = []
for text in processed_texts:
    all_words.extend(text.split())
word_counts = Counter(all_words)
top_10_words = word_counts.most_common(10)

# Топ-10 биграмм
bigram_vectorizer = CountVectorizer(ngram_range=(2, 2))
bigram_matrix = bigram_vectorizer.fit_transform(processed_texts)
bigram_sums = np.array(bigram_matrix.sum(axis=0)).flatten()
bigram_features = bigram_vectorizer.get_feature_names_out()
bigram_counts = [(bigram_features[i], bigram_sums[i]) for i in range(len(bigram_features))]
bigram_counts.sort(key=lambda x: x[1], reverse=True)
top_10_bigrams = bigram_counts[:10]

fig, axes = plt.subplots(1, 2, figsize=(16, 6))
fig.patch.set_facecolor('white')

# Топ-10 слов (слева)
ax1 = axes[0]
ax1.set_facecolor('white')

words, counts = zip(*top_10_words)
bars1 = ax1.barh(words, counts, color=colors[:len(words)], edgecolor='white', linewidth=1)
ax1.set_xlabel('Частота', fontweight='bold')
ax1.set_title('Топ-10 самых частотных слов', fontweight='bold', fontsize=14, pad=10)
ax1.grid(True, axis='x', alpha=0.3, linestyle='--')
ax1.set_axisbelow(True)

for i, (word, count) in enumerate(top_10_words):
    ax1.text(count + 0.5, i, f' {count}', va='center', fontweight='bold')

# Топ-10 биграмм (справа)
ax2 = axes[1]
ax2.set_facecolor('white')

bigrams, counts = zip(*top_10_bigrams)
bars2 = ax2.barh(bigrams, counts, color=colors[:len(bigrams)], edgecolor='white', linewidth=1)
ax2.set_xlabel('Частота', fontweight='bold')
ax2.set_title('Топ-10 самых частотных биграмм', fontweight='bold', fontsize=14, pad=10)
ax2.grid(True, axis='x', alpha=0.3, linestyle='--')
ax2.set_axisbelow(True)

for i, (bigram, count) in enumerate(top_10_bigrams):
    ax2.text(count + 0.2, i, f' {count}', va='center', fontweight='bold')

plt.tight_layout()
plt.show()

fig, axes = plt.subplots(2, 2, figsize=(16, 12))
fig.patch.set_facecolor('white')
fig.suptitle('Топ-10 самых частотных слов по каждой песне', fontsize=16, fontweight='bold', y=0.98)

for idx, (song, text) in enumerate(df_complete.iterrows()):
    ax = axes[idx // 2, idx % 2]
    ax.set_facecolor('white')

    words = text['Обработанный текст'].split()
    word_counts = Counter(words)
    top_10 = word_counts.most_common(10)

    if top_10:
        words_list, counts_list = zip(*top_10)

        bars = ax.bar(words_list, counts_list, color=colors[:len(words_list)], edgecolor='white', linewidth=1)

        for i, (word, count) in enumerate(top_10):
            ax.text(i, count + 0.1, str(count),
                   ha='center', va='bottom', fontweight='bold', fontsize=10)

        ax.set_ylabel('Частота', fontweight='bold', fontsize=11)
        ax.set_title(f'Песня: {song}', fontweight='bold', fontsize=13, pad=10)
        ax.grid(True, axis='y', alpha=0.3, linestyle='--')
        ax.set_axisbelow(True)

        plt.setp(ax.get_xticklabels(), rotation=45, ha='right', fontsize=9)

plt.tight_layout()
plt.subplots_adjust(top=0.93)
plt.show()

"""Анализ частотности слов и биграмм выявил ключевые тематики каждой песни. В песне "7 цифр" доминирует лексика ожидания и коммуникации: «любовь» (12), «найти» (11), «цифра» (10), «звонок» (7), что соответствует теме ожидания звонка. "Так красиво" полностью построена вокруг романтической лексики с аномально высокими повторениями слов «твой» (49) и «любовь» (49), а также устойчивыми биграммами «твой любовь» (53), что указывает на рефренную структуру текста. В песне "Я не боюсь" абсолютный лидер — слово «бояться» (24) и его повтор в биграмме «бояться бояться» (18), что создает эффект навязчивого мотива преодоления страха. "Идеальный мир" отличается более разнообразной лексикой с парными понятиями: *«мир» (6), «идеальный» (4), «простить» (4), «женщина/мужчина» (2/2)*, что отражает тему гармоничных отношений.

Общий топ-10 биграмм подтверждает, что ключевая тема всех песен это любовь и отношения («твой любовь» — 53, «любовь это» — 20, «это красиво» — 20), при этом каждая песня раскрывает ее через уникальную лексику: ожидание (7 цифр), восхищение (Так красиво), преодоление (Я не боюсь) и гармонию (Идеальный мир).
"""

all_text = ' '.join(processed_texts)

plt.figure(figsize=(14, 6))
wordcloud_all = WordCloud(
    width=1000, height=500,
    background_color='white',
    colormap='plasma',
    max_words=60
).generate(all_text)

plt.imshow(wordcloud_all, interpolation='bilinear')
plt.axis('off')
plt.title('Облако слов (униграммы): Все песни', fontweight='bold', fontsize=18, pad=20)
plt.tight_layout()
plt.show()

fig, axes = plt.subplots(2, 2, figsize=(16, 10))
fig.patch.set_facecolor('white')
fig.suptitle('Облака слов (униграммы) по отдельным песням', fontweight='bold', fontsize=18, y=0.98)

for idx, (song, text) in enumerate(zip(songs, processed_texts)):
    row = idx // 2
    col = idx % 2
    ax = axes[row, col]

    wordcloud = WordCloud(
        width=600, height=400,
        background_color='white',
        colormap='plasma',
        max_words=40, collocations=False
    ).generate(text)

    ax.imshow(wordcloud, interpolation='bilinear')
    ax.axis('off')

    for spine in ax.spines.values():
        spine.set_visible(True)
        spine.set_color(colors[idx])
        spine.set_linewidth(3)

    ax.set_title(song, fontweight='bold', fontsize=14, color='black', pad=10)

plt.tight_layout()
plt.show()

"""Облако слов полностью подтверждает выводы, полученные при анализе частотности слов и биграмм.

В песне "7 цифр" облако визуализирует доминирование лексики ожидания: «любовь» (12), «найти» (11), «цифра» (10) и «звонок» (7), что отражает тему ожидания звонка.

"Так красиво" выделяется аномально крупными словами «твой» (49) и «любовь» (49), которые занимают центральное место в облаке, визуально подтверждая романтическую направленность.

В облаке песни "Я не боюсь" слово «бояться» (24) доминирует очень сильно, что визуально подавляет остальную лексику, что соответствует эффекту навязчивого мотива преодоления страха, выявленному через биграмму «бояться бояться» (18).

"Идеальный мир" в облаке демонстрирует более равномерное распределение слов: «мир» (6), «идеальный» (4), «простить» (4), а также парные понятия «женщина/мужчина», что визуализирует тему гармоничных отношений.

Таким образом, облака слов служат наглядной визуализацией количественных данных.
"""

from sklearn.manifold import TSNE

tsne = TSNE(n_components=2, random_state=42, perplexity=2)
tsne_results = tsne.fit_transform(tfidf_matrix.toarray())

plt.figure(figsize=(10, 8))
scatter = plt.scatter(tsne_results[:, 0], tsne_results[:, 1], c=range(len(songs)), cmap='Set2', s=300, edgecolor='white', linewidth=2, zorder=2)

for i, song in enumerate(songs):
    plt.annotate(song,
                (tsne_results[i, 0], tsne_results[i, 1] + 8),
                fontsize=11, fontweight='bold', ha='center', va='bottom',
                bbox=dict(boxstyle='round,pad=0.2', facecolor='white', alpha=0.9,
                          edgecolor=plt.cm.Set2(i/len(songs))), zorder=3)

x_min, x_max = tsne_results[:, 0].min(), tsne_results[:, 0].max()
y_min, y_max = tsne_results[:, 1].min(), tsne_results[:, 1].max()
x_margin = (x_max - x_min) * 0.1
y_margin = (y_max - y_min) * 0.15

plt.xlim(x_min - x_margin, x_max + x_margin)
plt.ylim(y_min - y_margin, y_max + y_margin * 1.5)
plt.title('t-SNE визуализация песен', fontweight='bold', fontsize=16, pad=20)
plt.xlabel('t-SNE компонента 1', fontweight='bold')
plt.ylabel('t-SNE компонента 2', fontweight='bold')
plt.grid(True, alpha=0.2, linestyle='--')
plt.tight_layout()
plt.show()

"""**Анализ t-SNE:**

"Так красиво" и "7 цифр" расположены близко друг к другу, что указывает на лексическое сходство между песнями. Действительно, обе активно используют слова «любовь» и «твой», что подтверждается частотным анализом.

"Я не боюсь" выделяется на фоне остальных своей уникальной лексикой с доминированием слова «бояться», что делает её семантически отличной от романтических "7 цифр" и "Так красиво".

"Идеальный мир" занимает промежуточное положение — она ближе к "Я не боюсь", чем к двум другим, что может объясняться менее выраженной романтической лексикой и большим разнообразием слов.

Таким образом, t-SNE наглядно демонстрирует, что "7 цифр" и "Так красиво" образуют смысловой кластер.
"""

song_stats = []
for i, song in enumerate(songs):
    words = processed_texts[i].split()
    unique_words = set(words)

    # Уникальные слова для этой песни
    other_words = set()
    for j, text in enumerate(processed_texts):
        if j != i:
            other_words.update(text.split())
    unique_to_song = unique_words - other_words

    song_stats.append({
        'Песня': song,
        'Всего слов': len(words),
        'Уникальных слов': len(unique_words),
        'Уникальных (только в этой)': len(unique_to_song),
        'Разнообразие (%)': len(unique_words)/len(words)*100
    })

df_stats = pd.DataFrame(song_stats)
style_dataframe(df_stats, gradient=True, num=0)

""""Идеальный мир" и "Я не боюсь" — самые лексически богатые: высокий процент уникальных слов (64.5% и 54.5%) и много слов, которые не встречаются в других песнях (55 и 47).
"Так красиво" — самая бедная по лексике (21.6% разнообразия), но самая длинная (232 слова) — построена на повторах одних и тех же слов.
"7 цифр" — средняя по объёму и разнообразию (37.6%), много уникальных слов (40), но меньше повторений.

###**4. Используйте предварительно обученную модель BERT для классификации тональности отзывов о фильмах. (Вес задачи: 20%)**


Execution algorithm::
* ✅ 1.Data preparation:
*   Loading IMDB Dataset https://disk.yandex.ru/d/dhKpEgM4rQkLiQ;
*   Text Preprocessing;
*   Train/Test Split;
* ✅ 2. Работа с BERT:
* Загрузите предварительно обученную модель BERT и соответствующий ей токенизатор с сайта Hugging Face:
* Hugging Face Transformers
* Токенизация
* Создание классификатора
* Подготовка данных: используйте токенизатор BERT для преобразования текстов в формат входных данных модели (входные идентификаторы, маски внимания и т. д.).

* ✅ 3. Обучение модели BERT:
* Тонкая настройка BERT: обучите модель на обучающем наборе данных и оцените ее качество на тестовом наборе данных;
* Оценка метрик:
* Точность
* Точность/Полнота
* F1-мера

Результаты части 4:
* ✅ Точность на тестовом наборе данных не ниже заданного порогового значения (например, 0,9).
* ✅ F1-мера для положительного класса близка к точности, что указывает на баланс между точностью и полнотой.
* ✅ Модель корректно различает явно положительные и явно отрицательные отзывы при ручной проверке примеров.
* ✅ Результаты стабильны при повторном разделении на обучающую и тестовую выборки (значительного снижения показателей не наблюдается).
* ✅ Время вывода на один отзыв достаточно короткое для практического использования (например, доли секунды на типичном GPU/CPU).
* ✅ Алгоритм обучения модели на основе задачи завершен;
* ✅ Все данные должны сопровождаться выводами, основанными на полученных результатах исследования (2-3 предложения);

Сниженная оценка:
* Модель не из Hugging Face / не BERT / не предварительно обучена;
* Отсутствует отдельная загрузка токенизатора или используется неправильный;
* Код существует, но не запускается из-за незначительных ошибок (импорт, имя модели);
* Тексты не токенизированы токенизатором BERT;
* Поля Input_ids и attention_mask (или аналогичные обязательные поля) не генерируются;
* Некорректные параметры токенизации (например, отсутствует заполнение/обрезка при необходимости);
* Отсутствует дополнительный линейный слой для бинарной классификации;
* Линейный слой присутствует, но количество выходов указано неверно / отсутствует активация на выходе при вычислении прогнозов;
* Модель вообще не обучалась;
* Отсутствует разделение между обучающим и тестовым наборами данных;
* Не выполняется расчет указанных метрик (точность, F1 или аналогичные);
* Метрики рассчитываются некорректно (например, на основе обучающих данных или из-за ошибки в коде);
* Код полностью идентичен примеру или работам других студентов.
"""

!pip install torch
!pip install transformers datasets pandas numpy tqdm scikit-learn

import torch
import pandas as pd
from sklearn.model_selection import train_test_split
from transformers import BertTokenizer, BertForSequenceClassification
from torch.utils.data import DataLoader, Dataset
from torch.optim import AdamW
from transformers import get_linear_schedule_with_warmup
import warnings
warnings.filterwarnings('ignore')
from torch.cuda.amp import autocast, GradScaler
import time
from tqdm import tqdm
import numpy as np
import os
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
import matplotlib.pyplot as plt
from datetime import datetime
import json
from google.colab import files
import shutil

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Используется устройство: {device}")

df = pd.read_csv("IMDB Dataset.csv")
print(f"Размер данных: {df.shape}")
print(f"Колонки: {df.columns.tolist()}")
print(f"\nРаспределение классов:\n{df['sentiment'].value_counts()}")
df.head()

"""Преобразование меток в числа (0 - negative, 1 - positive)

Разделение данных на train (80%) и test (20%)


"""

random_state = 42
df['label'] = df['sentiment'].map({'negative': 0, 'positive': 1})
print("После преобразования:")
print(df[['sentiment', 'label']].head())
train_texts, test_texts, train_labels, test_labels = train_test_split(df['review'].values, df['label'].values, test_size=0.2, random_state=42, stratify=df['label'])

print(f"\nРазмер обучающей выборки: {len(train_texts)}")
print(f"Размер тестовой выборки: {len(test_texts)}")

"""Загрузка BERT и токенизатора"""

model_name = 'bert-base-uncased'
model = BertForSequenceClassification.from_pretrained(
    model_name,
    num_labels=2,
    output_attentions=False,
    output_hidden_states=False
)
tokenizer = BertTokenizer.from_pretrained(model_name)

model = model.to(device)

"""Токенизация, создание классификатора, подготовка данных"""

def create_data_loaders(train_texts, train_labels, test_texts, test_labels, tokenizer, max_len=256, batch_size=64):
    """
    Создает DataLoader для обучающей и тестовой выборок.
    """
    train_dataset = IMDbDataset(train_texts, train_labels, tokenizer, max_len)
    test_dataset = IMDbDataset(test_texts, test_labels, tokenizer, max_len)

    train_loader = DataLoader(
        train_dataset,
        batch_size=batch_size,
        shuffle=True,
        num_workers=2,
        drop_last=False,
        pin_memory=True,
        prefetch_factor=2
    )

    test_loader = DataLoader(
        test_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=2,
        drop_last=False,
        pin_memory=True,
        prefetch_factor=2
    )

    print(f"Данные: {len(train_texts)} обучающих, {len(test_texts)} тестовых")
    print(f"Размер батча: {batch_size}")

    return train_loader, test_loader

class IMDbDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_len=256):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = str(self.texts[idx])
        label = self.labels[idx]
        encoding = self.tokenizer(text, truncation=True, padding='max_length', max_length=self.max_len, return_tensors='pt')
        return {'input_ids': encoding['input_ids'].flatten(), 'attention_mask': encoding['attention_mask'].flatten(), 'labels': torch.tensor(label, dtype=torch.long)}

train_loader, test_loader = create_data_loaders(
    train_texts, train_labels,
    test_texts, test_labels,
    tokenizer,
)

"""Настройка оптимизатора"""

optimizer = AdamW([
    {'params': model.bert.encoder.layer[-4:].parameters(), 'lr': 2e-5},
    {'params': model.classifier.parameters(), 'lr': 2e-5},
], lr=1e-5)

# Количество эпох
epochs = 2
total_steps = len(train_loader) * epochs

scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=int(0.1 * total_steps),
    num_training_steps=total_steps
)
scaler = GradScaler()

"""Обучение модели"""

def train_epoch(model, data_loader, optimizer, scheduler, device, scaler, accumulation_steps=2, epoch_idx=0, grad_clip=1.0):
    model.train()
    losses = []
    correct_predictions = 0
    total_predictions = 0
    optimizer.zero_grad()

    batch_history = {
        'batch_steps': [],
        'batch_losses': [],
        'batch_accs': [],
        'learning_rates': [],
        'grad_norms': []
    }

    progress_bar = tqdm(data_loader, desc=f"Эпоха {epoch_idx}")

    for i, batch in enumerate(progress_bar):
        input_ids = batch['input_ids'].to(device, non_blocking=True)
        attention_mask = batch['attention_mask'].to(device, non_blocking=True)
        labels = batch['labels'].to(device, non_blocking=True)

        with autocast(dtype=torch.float16):
            outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
            loss = outputs.loss / accumulation_steps

        scaler.scale(loss).backward()

        if (i + 1) % accumulation_steps == 0:
            scaler.unscale_(optimizer)
            grad_norm = torch.nn.utils.clip_grad_norm_(model.parameters(), grad_clip)
            batch_history['grad_norms'].append(grad_norm.item())

            scaler.step(optimizer)
            scaler.update()
            scheduler.step()
            optimizer.zero_grad()

            batch_history['learning_rates'].append(optimizer.param_groups[0]['lr'])

        current_loss = loss.item() * accumulation_steps
        losses.append(current_loss)

        preds = torch.argmax(outputs.logits, dim=1)
        correct = torch.sum(preds == labels).item()
        batch_acc = correct / len(labels)
        correct_predictions += correct
        total_predictions += len(labels)

        current_epoch_acc = correct_predictions / total_predictions

        batch_history['batch_steps'].append(i)
        batch_history['batch_losses'].append(current_loss)
        batch_history['batch_accs'].append(batch_acc)

        progress_bar.set_postfix({
            'loss': f'{current_loss:.4f}',
            'avg_loss': f'{np.mean(losses):.4f}',
            'batch_acc': f'{batch_acc:.4f}',
            'epoch_acc': f'{current_epoch_acc:.4f}',
            'lr': f'{optimizer.param_groups[0]["lr"]:.2e}'
        })

    epoch_accuracy = correct_predictions / len(data_loader.dataset)

    return np.mean(losses), epoch_accuracy, batch_history

def eval_model(model, data_loader, device):
    model.eval()
    losses = []
    all_preds = []
    all_labels = []
    all_probs = []

    progress_bar = tqdm(data_loader, desc="Оценка")

    with torch.no_grad():
        for batch in progress_bar:
            input_ids = batch['input_ids'].to(device, non_blocking=True)
            attention_mask = batch['attention_mask'].to(device, non_blocking=True)
            labels = batch['labels'].to(device, non_blocking=True)

            with autocast(dtype=torch.float16):
                outputs = model(
                    input_ids=input_ids,
                    attention_mask=attention_mask,
                    labels=labels
                )

            loss = outputs.loss
            logits = outputs.logits
            probs = torch.softmax(logits, dim=1)

            losses.append(loss.item())
            preds = torch.argmax(logits, dim=1)

            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())
            all_probs.extend(probs.cpu().numpy())

            current_acc = accuracy_score(all_labels, all_preds)

            progress_bar.set_postfix({
                'loss': f'{loss.item():.4f}',
                'avg_loss': f'{np.mean(losses):.4f}',
                'acc': f'{current_acc:.4f}'
            })

    accuracy = accuracy_score(all_labels, all_preds)
    precision, recall, f1, _ = precision_recall_fscore_support(
        all_labels, all_preds, average='binary'
    )

    return np.mean(losses), accuracy, precision, recall, f1, all_preds, all_labels, all_probs

history = {
    random_state: {
        'train_loss': [],
        'train_acc': [],
        'test_loss': [],
        'test_acc': [],
        'test_precision': [],
        'test_recall': [],
        'test_f1': []
    }
}

history_batch = []


for epoch in range(epochs):
    print(f"\nЭпоха {epoch + 1}/{epochs}")

    # Обучение
    train_loss, train_acc, batch_history = train_epoch(
        model, train_loader, optimizer, scheduler, device, scaler,
        accumulation_steps=2, epoch_idx=epoch+1
    )

    # Оценка
    test_loss, test_acc, test_precision, test_recall, test_f1, test_preds, test_labels, test_probs = eval_model(
        model, test_loader, device
    )

    # Сохранение истории
    history[random_state]['train_loss'].append(train_loss)
    history[random_state]['train_acc'].append(train_acc)
    history[random_state]['test_loss'].append(test_loss)
    history[random_state]['test_acc'].append(test_acc)             # Был пропущен [random_state]
    history[random_state]['test_precision'].append(test_precision) # Был пропущен [random_state]
    history[random_state]['test_recall'].append(test_recall)       # Был пропущен [random_state]
    history[random_state]['test_f1'].append(test_f1)               # Был пропущен [random_state]

    history_batch.append({
        'random_state': random_state,
        'epoch': epoch,
        'batch_history': batch_history
    })

    # Вывод результатов
    print(f"\nРезультаты эпохи {epoch + 1}:")
    print(f"Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.4f}")
    print(f"Test Loss: {test_loss:.4f} | Test Acc: {test_acc:.4f}")
    print(f"Precision: {test_precision:.4f} | Recall: {test_recall:.4f} | F1: {test_f1:.4f}")

# Финальная оценка
test_loss, test_acc, test_precision, test_recall, test_f1, y_pred, y_true, y_probs = eval_model(
    model, test_loader, device
)

final_predictions = {
    'preds': y_pred,        # массив с предсказаниями (0 или 1)
    'labels': y_true,       # массив с истинными метками
    'probs': y_probs,       # массив с вероятностями для каждого класса
    'loss': test_loss,      # финальное значение loss
    'accuracy': test_acc,   # финальная точность
    'precision': test_precision,
    'recall': test_recall,
    'f1': test_f1
}

print(f"\nТочность (Accuracy): {test_acc:.4f}")
print(f"Точность (Precision): {test_precision:.4f}")
print(f"Полнота (Recall): {test_recall:.4f}")
print(f"F1-мера: {test_f1:.4f}")

"""Модель демонстрирует стабильное обучение без признаков переобучения. Наблюдается положительная динамика: по итогам второй эпохи точность на обучающей выборке достигла 87.92% , а на тестовой — 89.07%. Небольшое превышение тестовой точности над тренировочной (вместе с более низким значением loss на тесте) указывает на хорошую способность модели к обобщению.

Метрики качества хорошо сбалансированы: полнота (91.16% ) незначительно превосходит точность (87.50% ). Это означает, что модель одинаково эффективно справляется с обеими задачами: она чуть лучше находит все положительные отзывы (меньше пропусков), при этом сохраняя высокую точность своих предсказаний. Высокий F1-показатель (89.29% ) подтверждает устойчивую и сбалансированную работу классификатора.
"""

def plot_training_history(history, history_batch, random_state=None, target_acc=0.9):
    """
    Функция для построения графиков обучения
    """

    hist = history[random_state]
    title_suffix = f" (random_state={random_state})"

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 5))
    fig.suptitle(f'Графики обучения{title_suffix}', fontsize=14, fontweight='bold')

    all_steps = []
    all_losses = []
    all_accs = []
    val_steps = []
    val_losses = []
    val_accs = []

    current_step = 0

    for epoch_idx, batch_item in enumerate(history_batch):
        batch_hist = batch_item['batch_history']
        n_batches = len(batch_hist['batch_steps'])

        for i in range(n_batches):
            all_steps.append(current_step + i)
            all_losses.append(batch_hist['batch_losses'][i])
            all_accs.append(batch_hist['batch_accs'][i])

        val_steps.append(current_step + n_batches)
        val_losses.append(hist['test_loss'][epoch_idx])
        val_accs.append(hist['test_acc'][epoch_idx])

        ax1.axvline(x=current_step + n_batches, color='gray', linestyle='--', alpha=0.3)
        ax2.axvline(x=current_step + n_batches, color='gray', linestyle='--', alpha=0.3)

        current_step += n_batches

    # График потерь
    ax1.plot(all_steps, all_losses, 'b-', label='Train Loss', alpha=0.6, linewidth=1)
    ax1.plot(val_steps, val_losses, 'ro', label='Val Loss', markersize=6, linewidth=2)
    ax1.set_xlabel('Шаг обучения')
    ax1.set_ylabel('Loss')
    ax1.set_title('Динамика потерь')
    ax1.legend()
    ax1.grid(True, alpha=0.3)

    # График точности
    ax2.plot(all_steps, all_accs, 'b-', label='Train Acc', alpha=0.6, linewidth=1)
    ax2.plot(val_steps, val_accs, 'ro', label='Val Acc', markersize=6, linewidth=2)
    ax2.axhline(y=target_acc, color='r', linestyle='--', alpha=0.5, label=f'Цель ({target_acc})')
    ax2.set_xlabel('Шаг обучения')
    ax2.set_ylabel('Accuracy')
    ax2.set_title('Динамика точности')
    ax2.legend()
    ax2.grid(True, alpha=0.3)

    for i, (step, acc) in enumerate(zip(val_steps, val_accs)):
        ax2.annotate(f'E{i+1}', (step, acc), xytext=(5, 5), textcoords='offset points', fontsize=10, color='red', weight='bold')

    final_acc = hist['test_acc'][-1]
    ax2.set_title(f'Динамика точности (Финальная: {final_acc:.4f})')

    plt.tight_layout()
    plt.show()

    print(f"\nСтатистика для{title_suffix}:")
    print(f"  Финальная точность: {hist['test_acc'][-1]:.4f}")
    print(f"  Финальный F1-score: {hist['test_f1'][-1]:.4f}")
    print(f"  Лучшая точность на валидации: {max(hist['test_acc']):.4f} (эпоха {np.argmax(hist['test_acc'])+1})")

plot_training_history(history, history_batch, random_state=random_state)

"""Модель обучается стабильно, без переобучения. Графики демонстрируют типичную для BERT динамику: быстрое обучение в первой эпохе и плавное улучшение во второй."""

def save_model_with_seed(model, tokenizer, history, history_batch, final_predictions, batch_size, max_len, random_state, save_dir="./saved_model"):
    """
    Функция для сохранения модели с указанием seed
    """

    os.makedirs(save_dir, exist_ok=True)

    # Получаем историю для конкретного seed
    hist = history[random_state]
    final_acc = hist['test_acc'][-1]

    date = datetime.now().strftime("%Y%m%d")
    model_name_save = f"bert_imdb_seed{random_state}_acc{final_acc:.4f}_{date}"
    save_path = f"{save_dir}/{model_name_save}"

    print(f"\n{'='*50}")
    print(f"Сохранение модели для seed = {random_state}")
    print(f"{'='*50}")
    print(f"Сохраняем модель в: {save_path}")

    os.makedirs(save_path, exist_ok=True)

    # Сохраняем модель и токенизатор
    model.save_pretrained(save_path)
    print("Модель сохранена")
    tokenizer.save_pretrained(save_path)
    print("Токенизатор сохранен")

    # Сохраняем историю обучения
    history_path = f"{save_path}/training_history.pt"
    torch.save(hist, history_path)
    print(f"История обучения сохранена: training_history.pt")

    # Сохраняем batch историю
    batch_history_path = f"{save_path}/batch_history.pt"
    seed_batch_history = [bh for bh in history_batch  if (isinstance(bh, dict) and bh.get('random_state') == random_state) or (isinstance(bh, list) and len(bh) == 2 and bh[0] == random_state)]
    torch.save(seed_batch_history, batch_history_path)
    print(f"Batch история сохранена: batch_history.pt")

    # Сохраняем финальные предсказания
    if final_predictions:
        preds_path = f"{save_path}/final_predictions.pt"
        torch.save(final_predictions, preds_path)
        print(f"Финальные предсказания сохранены: final_predictions.pt")

    # Метаданные
    metadata = {
        'random_state': random_state,
        'final_accuracy': float(hist['test_acc'][-1]),
        'final_loss': float(hist['test_loss'][-1]),
        'final_precision': float(hist['test_precision'][-1]),
        'final_recall': float(hist['test_recall'][-1]),
        'final_f1': float(hist['test_f1'][-1]),
        'train_acc': [float(x) for x in hist['train_acc']],
        'train_loss': [float(x) for x in hist['train_loss']],
        'test_acc': [float(x) for x in hist['test_acc']],
        'test_loss': [float(x) for x in hist['test_loss']],
        'test_precision': [float(x) for x in hist['test_precision']],
        'test_recall': [float(x) for x in hist['test_recall']],
        'test_f1': [float(x) for x in hist['test_f1']],
        'epochs': len(hist['train_loss']),
        'batch_size': batch_size,
        'max_len': max_len,
        'model_name': 'bert-base-uncased',
        'optimizer': 'AdamW',
        'scheduler': 'linear_with_warmup',
        'accumulation_steps': 2,
        'date': date,
        'save_path': save_path
    }

    metadata_path = f"{save_path}/metadata.json"
    with open(metadata_path, 'w', encoding='utf-8') as f:
        json.dump(metadata, f, indent=2, ensure_ascii=False)
    print(f"Метаданные сохранены: metadata.json")

    summary = f"""
    {'='*60}
    BERT IMDB SENTIMENT ANALYSIS
    {'='*60}

    Модель: bert-base-uncased
    Seed (random_state): {random_state}
    Дата: {datetime.now().strftime('%Y-%m-%d')}

    РЕЗУЛЬТАТЫ:
    - Точность (Accuracy): {hist['test_acc'][-1]:.4f}
    - Потери (Loss): {hist['test_loss'][-1]:.4f}
    - Precision: {hist['test_precision'][-1]:.4f}
    - Recall: {hist['test_recall'][-1]:.4f}
    - F1-score: {hist['test_f1'][-1]:.4f}

    Динамика по эпохам:
    """

    for epoch in range(len(hist['train_loss'])):
        summary += f"""
    Эпоха {epoch+1}:
      Train Loss: {hist['train_loss'][epoch]:.4f} | Train Acc: {hist['train_acc'][epoch]:.4f}
      Test Loss: {hist['test_loss'][epoch]:.4f} | Test Acc: {hist['test_acc'][epoch]:.4f}
      Precision: {hist['test_precision'][epoch]:.4f} | Recall: {hist['test_recall'][epoch]:.4f} | F1: {hist['test_f1'][epoch]:.4f}
    """

    summary += f"""
    Параметры:
    - Эпох: {len(hist['train_loss'])}
    - Размер батча: {batch_size}
    - Макс. длина: {max_len}
    - Накопление градиентов: 2

    файлы:
    - Модель: {save_path}
    - История: training_history.pt
    - Batch история: batch_history.pt
    - Метаданные: metadata.json
    {'='*60}
    """

    summary_path = f"{save_path}/summary.txt"
    with open(summary_path, 'w', encoding='utf-8') as f:
        f.write(summary)
    return save_path

save_path = save_model_with_seed(
    model=model,                    # ваша обученная модель
    tokenizer=tokenizer,             # токенизатор
    history=history,                 # словарь с историей {seed: {...}}
    history_batch=history_batch,     # список с batch историей
    final_predictions=final_predictions,  # финальные предсказания
    batch_size=64,                   # ваш batch_size
    max_len=256,                     # ваш max_len
    random_state=42,                  # seed, для которого сохраняем
    save_dir="./saved_model"          # директория для сохранения
)

print(f"\nМодель сохранена по пути: {save_path}")

def zip_model(model_path, download=True):
    """
    Функция для создания zip-архива модели
    """
    if not os.path.exists(model_path):
        print(f"Ошибка: Папка {model_path} не найдена!")
        return None

    model_name = os.path.basename(model_path)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    zip_filename = f"{model_name}_{timestamp}"
    zip_path = f"/content/{zip_filename}"

    print(f"Создание архива...")
    print(f"  Исходная папка: {model_path}")
    print(f"  Архив: {zip_filename}.zip")

    shutil.make_archive(zip_path, 'zip', model_path)

    full_zip_path = f"{zip_path}.zip"
    zip_size = os.path.getsize(full_zip_path) / (1024 * 1024)

    print(f"Архив создан: {full_zip_path}")
    print(f"Размер: {zip_size:.2f} MB")

    return full_zip_path

zip_model('/content/saved_model/bert_imdb_seed42_acc0.8907_20260301')

def train_with_seeds(df, random_states, device, tokenizer, epochs=3, batch_size=64, max_len=256, save_dir="./saved_model"):
    """
    Функция для обучения модели на разных random_state
    """

    all_history = {}
    all_batch_history = []
    all_predictions = {}
    models_dict = {}

    print(f"Seed: {random_states}")
    print(f"Параметры: epochs={epochs}, batch_size={batch_size}, max_len={max_len}")

    for seed_idx, rs in enumerate(random_states):
        print(f"\n{'#'*50}")
        print(f"Номер {seed_idx + 1}/{len(random_states)} | random_state = {rs}")
        print(f"{'#'*50}")

        # Разделение данных
        train_texts, test_texts, train_labels, test_labels = train_test_split(df['review'].values, df['label'].values, test_size=0.2, random_state=rs, stratify=df['label'])

        # Создание DataLoader
        train_loader, test_loader = create_data_loaders(train_texts, train_labels, test_texts, test_labels, tokenizer, max_len, batch_size)

        # Инициализация новой модели для каждого seed
        print(f"\nИнициализация модели для seed={rs}...")
        model = BertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=2, output_attentions=False, output_hidden_states=False).to(device)
        model_name = 'bert-base-uncased'

        # Инициализация оптимизатора
        optimizer = AdamW([
            {'params': model.bert.encoder.layer[-4:].parameters(), 'lr': 2e-5},
            {'params': model.classifier.parameters(), 'lr': 2e-5},
        ], lr=1e-5)

        # Инициализация scheduler
        total_steps = len(train_loader) * epochs
        scheduler = get_linear_schedule_with_warmup(
            optimizer,
            num_warmup_steps=int(0.1 * total_steps),
            num_training_steps=total_steps
        )

        # Инициализация scaler
        scaler = GradScaler()

        # Создание словаря истории для текущего seed
        history = {
            rs: {
                'train_loss': [],
                'train_acc': [],
                'test_loss': [],
                'test_acc': [],
                'test_precision': [],
                'test_recall': [],
                'test_f1': []
            }
        }

        history_batch = []

        # Цикл обучения
        for epoch in range(epochs):
            print(f"\n--- Эпоха {epoch + 1}/{epochs} ---")

            # Обучение
            train_loss, train_acc, batch_history = train_epoch(
                model, train_loader, optimizer, scheduler, device, scaler,
                accumulation_steps=2, epoch_idx=epoch+1
            )

            # Оценка
            test_loss, test_acc, test_precision, test_recall, test_f1, test_preds, test_labels, test_probs = eval_model(
                model, test_loader, device
            )

            # Сохранение в историю
            history[rs]['train_loss'].append(train_loss)
            history[rs]['train_acc'].append(train_acc)
            history[rs]['test_loss'].append(test_loss)
            history[rs]['test_acc'].append(test_acc)
            history[rs]['test_precision'].append(test_precision)
            history[rs]['test_recall'].append(test_recall)
            history[rs]['test_f1'].append(test_f1)

            # Сохранение batch истории
            history_batch.append({
                'random_state': rs,
                'epoch': epoch,
                'batch_history': batch_history
            })

            print(f"\nРезультаты эпохи {epoch + 1}:")
            print(f"Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.4f}")
            print(f"Test Loss: {test_loss:.4f} | Test Acc: {test_acc:.4f}")
            print(f"Precision: {test_precision:.4f} | Recall: {test_recall:.4f} | F1: {test_f1:.4f}")

        # Сохраняем финальные предсказания
        final_predictions = {
            'preds': test_preds,
            'labels': test_labels,
            'probs': test_probs
        }

        all_history[rs] = history[rs]
        all_batch_history.extend(history_batch)
        all_predictions[rs] = final_predictions
        models_dict[rs] = model


        save_path = save_model_with_seed(
            model=model,
            tokenizer=tokenizer,
            history=history,
            history_batch=all_batch_history,
            final_predictions=final_predictions,
            batch_size=batch_size,
            max_len=max_len,
            random_state=rs,
            save_dir=save_dir
        )

    return all_history, all_batch_history, all_predictions, models_dict

random_states = [123, 211]

all_history, all_batch_history, all_predictions, models_dict = train_with_seeds(
    df=df,
    random_states=random_states,
    device=device,
    tokenizer=tokenizer,
    epochs=2,
    batch_size=64,
    max_len=256,
    save_dir="./saved_model"
)

"""Анализ двух экспериментов с разными seed показывает стабильные и сопоставимые результаты. Модель с random_state=123 к концу обучения достигла точности 0.8890 при F1-score 0.8876, показав хороший баланс между точностью и полнотой. Еще более убедительный результат получен с random_state=211: точность на тесте составила 0.9000, а F1-score достиг 0.9007, что свидетельствует о выходе на целевой уровень качества."""

zip_model('/content/saved_model/bert_imdb_seed123_acc0.8890_20260301')
zip_model('/content/saved_model/bert_imdb_seed211_acc0.9000_20260301')

all_history = {**all_history, **history}
print(f"Объединенная all_history содержит seed: {list(all_history.keys())}")

# Объединяем batch истории
all_batch_history = all_batch_history + history_batch
print(f"all_batch_history до: {len(all_batch_history) - len(history_batch)} записей")
print(f"history_batch: {len(history_batch)} записей")
print(f"all_batch_history после: {len(all_batch_history)} записей")

def plot_seeds_comparison(all_history, all_batch_history, seeds=None, target_acc=0.9, figsize=(15, 6)):
    """
    Функция для сравнения нескольких seed на одном графике с динамикой по шагам
    """

    if seeds is None:
        seeds = list(all_history.keys())

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=figsize)
    fig.suptitle(f'Сравнение динамики обучения для разных seed', fontsize=14, fontweight='bold')

    colors = ['#FF6B6B', '#4ECDC4', '#45B7D1', '#96CEB4', '#FFE194', '#E6B89C', '#FE938C', '#9C89B8', '#B8F2E6', '#AFAF9C']

    # Динамика потерь (Loss)
    ax1.set_title('Динамика потерь (по шагам обучения)', fontsize=12)
    ax1.set_xlabel('Шаг обучения')
    ax1.set_ylabel('Loss')
    ax1.grid(True, alpha=0.3)

    # Динамика точности (Accuracy)
    ax2.set_title('Динамика точности (по шагам обучения)', fontsize=12)
    ax2.set_xlabel('Шаг обучения')
    ax2.set_ylabel('Accuracy')
    ax2.axhline(y=target_acc, color='red', linestyle='--', alpha=0.5, label=f'Цель ({target_acc})')
    ax2.grid(True, alpha=0.3)

    for idx, seed in enumerate(seeds):
        hist = all_history[seed]
        color = colors[idx]

        # Фильтруем batch_history для этого seed
        seed_batch = [b for b in all_batch_history if b.get('random_state') == seed]
        all_steps = []
        all_losses = []
        all_accs = []
        val_steps = []
        val_losses = []
        val_accs = []

        current_step = 0
        epochs = len(seed_batch)

        for epoch_idx, batch_item in enumerate(seed_batch):
            batch_hist = batch_item['batch_history']
            n_batches = len(batch_hist['batch_steps'])

            for i in range(n_batches):
                all_steps.append(current_step + i)
                all_losses.append(batch_hist['batch_losses'][i])
                all_accs.append(batch_hist['batch_accs'][i])

            val_steps.append(current_step + n_batches)
            val_losses.append(hist['test_loss'][epoch_idx])
            val_accs.append(hist['test_acc'][epoch_idx])

            current_step += n_batches

        # Train (побатчево)
        ax1.plot(all_steps, all_losses, color=color, linestyle='-', alpha=0.3, linewidth=0.8, label=f'Seed {seed} (train)')
        ax2.plot(all_steps, all_accs, color=color, linestyle='-', alpha=0.3, linewidth=0.8, label=f'Seed {seed} (train)')

        # Validation (точки в конце эпох)
        ax1.plot(val_steps, val_losses, color=color, marker='o', linestyle='None', markersize=8, label=f'Seed {seed} (val)')
        ax2.plot(val_steps, val_accs, color=color, marker='s', linestyle='None', markersize=8, label=f'Seed {seed} (val)')

        for i, (step, acc) in enumerate(zip(val_steps, val_accs)):
            ax2.annotate(f'E{i+1}', (step, acc), xytext=(5, 5), textcoords='offset points', fontsize=8, color=color, weight='bold')

        for step in val_steps[:-1]:
            ax1.axvline(x=step, color=color, linestyle='--', alpha=0.2)
            ax2.axvline(x=step, color=color, linestyle='--', alpha=0.2)

    ax1.legend(loc='upper right', fontsize=8, ncol=2)
    ax2.legend(loc='lower right', fontsize=8, ncol=2)

    plt.tight_layout()
    plt.show()

    print("\nСводная таблица результатов:")
    print("=" * 80)
    print(f"{'Seed':<8} {'Accuracy':<12} {'Precision':<12} {'Recall':<12} {'F1-score':<12} {'Эпох':<8}")
    print("-" * 80)

    for seed in seeds:
        if seed in all_history:
            hist = all_history[seed]
            print(f"{seed:<8} {hist['test_acc'][-1]:<12.4f} "
                  f"{hist['test_precision'][-1]:<12.4f} "
                  f"{hist['test_recall'][-1]:<12.4f} "
                  f"{hist['test_f1'][-1]:<12.4f} "
                  f"{len(hist['train_loss']):<8}")

    print("=" * 80)

    # Статистика
    valid_seeds = [s for s in seeds if s in all_history]
    if valid_seeds:
        accs = [all_history[s]['test_acc'][-1] for s in valid_seeds]
        print(f"\nСтатистика по {len(valid_seeds)} seed:")
        print(f"  Средняя точность: {np.mean(accs):.4f} ± {np.std(accs):.4f}")
        print(f"  Минимальная: {np.min(accs):.4f} (seed {valid_seeds[np.argmin(accs)]})")
        print(f"  Максимальная: {np.max(accs):.4f} (seed {valid_seeds[np.argmax(accs)]})")
        print(f"  Размах: {np.max(accs) - np.min(accs):.4f}")

plot_seeds_comparison(all_history, all_batch_history)

"""Анализ графиков и сводной таблицы показывает высокую стабильность обучения при различных значениях seed. Динамика потерь для всех трех экспериментов синхронно снижается, а кривые точности растут. Это подтверждает, что выбранная конфигурация модели и гиперпараметров обеспечивает воспроизводимый результат независимо от начальной инициализации.

Средняя точность по трем запускам составила 0.8932 ± 0.0048, что говорит об очень низком разбросе результатов — всего 1.1% между минимальным (0.889) и максимальным (0.9) значением. Лучший результат показал seed 211 с точностью 0.9 и сбалансированными метриками (F1-score 0.9007).

Таким образом, модель демонстрирует устойчивое обучение с минимальной зависимостью от random seed. Стабильность метрик во всех запусках свидетельствует о надежности подхода: независимо от начальной инициализации модель выдает предсказуемо высокие результаты без признаков переобучения.

Тестирование загруженной модели
"""

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model_path = '/content/saved_model/bert_imdb_seed211_acc0.9000_20260301'

model_test = BertForSequenceClassification.from_pretrained(model_path).to(device)
model_test.eval()

test_size = 0.2
_, test_texts, _, test_labels = train_test_split(df['review'].values, df['label'].values, test_size=test_size, random_state=122, stratify=df['label'])

print(f"Размер тестовой выборки: {len(test_texts)}")

max_len = 256
batch_size = 64

test_dataset = IMDbDataset(test_texts, test_labels, tokenizer, max_len)
test_loader = DataLoader(
    test_dataset,
    batch_size=batch_size,
    shuffle=False,
    num_workers=2,
    pin_memory=True,
    prefetch_factor=2
)

print("\nОценка модели на тестовых данных...")
test_loss, test_acc, test_precision, test_recall, test_f1, y_pred, y_true, y_probs = eval_model(
    model_test, test_loader, device
)

print(f"\nТочность (Accuracy): {test_acc:.4f}")
print(f"Точность (Precision): {test_precision:.4f}")
print(f"Полнота (Recall): {test_recall:.4f}")
print(f"F1-мера: {test_f1:.4f}")

"""Модель, обученная с random_state=211, была протестирована на выборке из 10000 примеров и подтвердила свою эффективность. Итоговая точность составила 0.9019, что даже немного превышает результат, полученный на валидации (0.9000). Все метрики сбалансированы: точность (0.8994) и полнота (0.9050) находятся на одном уровне, обеспечивая F1-меру 0.9022. Это говорит о том, что модель одинаково хорошо распознает оба класса и не переобучена под конкретную выборку."""

def predict_sentiment(text, model, tokenizer, device):
    model.eval()
    encoding = tokenizer(text, truncation=True, padding='max_length',
                        max_length=256, return_tensors='pt')
    input_ids = encoding['input_ids'].to(device)
    attention_mask = encoding['attention_mask'].to(device)

    with torch.no_grad():
        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        probs = torch.softmax(outputs.logits, dim=1)
        prediction = torch.argmax(probs, dim=1).item()

    sentiment = 'positive' if prediction == 1 else 'negative'
    confidence = probs[0][prediction].item()

    return sentiment, confidence

# Примеры для проверки
test_reviews = [
    "This movie was absolutely fantastic! Great acting and storyline.",
    "Terrible film, wasted my time. Poor acting and boring plot.",
    "It was okay, nothing special but not terrible either."
]

for review in test_reviews:
    sentiment, conf = predict_sentiment(review, model_test, tokenizer, device)
    print(f"Итог: {review}")
    print(f"Prediction: {sentiment} (confidence: {conf:.4f})\n")

"""Модель правильно классифицировала все три тестовых отзыва с высокой уверенностью. Явно позитивный отзыв определен как positive (0.9808), явно негативный — как negative (0.9742). Нейтральный отзыв, который можно трактовать двояко, модель отнесла к положительным с чуть меньшей уверенностью (0.8466), что тоже допустимо, так как в нём нет явного негатива.

Тестирование времени
"""

def measure_inference_time(model, test_loader, device, num_batches=10):
    """
    Измеряет время инференса модели
    """
    # Убеждаемся, что модель на правильном устройстве
    model = model.to(device)
    model.eval()
    times = []

    print(f"Измерение времени инференса на {num_batches} батчах...")
    print(f"Размер батча: {test_loader.batch_size}")
    print(f"Устройство: {device}")
    print("-" * 50)

    with torch.no_grad():
        for i, batch in enumerate(test_loader):
            if i >= num_batches:
                break

            # Перемещаем данные на то же устройство, что и модель
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)

            if device.type == 'cuda':
                torch.cuda.synchronize()

            start_time = time.perf_counter()

            outputs = model(input_ids=input_ids, attention_mask=attention_mask)

            if device.type == 'cuda':
                torch.cuda.synchronize()

            end_time = time.perf_counter()

            batch_time = end_time - start_time
            times.append(batch_time)

            print(f"Батч {i+1}: {batch_time*1000:.2f} мс")

    # Статистика
    times_ms = np.array(times) * 1000
    avg_time_per_batch = np.mean(times)
    avg_time_per_sample = avg_time_per_batch / test_loader.batch_size
    std_time_per_batch = np.std(times)

    print("-" * 50)
    print(f"Результаты:")
    print(f"   Среднее время на батч: {avg_time_per_batch*1000:.2f} мс ± {std_time_per_batch*1000:.2f} мс")
    print(f"   Среднее время на 1 отзыв: {avg_time_per_sample*1000:.2f} мс")
    print(f"   Пропускная способность: {1/avg_time_per_sample:.1f} отзывов/сек")

    return avg_time_per_sample

# Способ 1: После обучения модели
print("\nТЕСТ 1: После обучения модели")
inference_time = measure_inference_time(
    model=model,  # ваша обученная модель
    test_loader=test_loader,  # тестовый DataLoader
    device=device,
    num_batches=20  # измеряем на 20 батчах для статистики
)

# Способ 2: Для загруженной модели
print("\nТЕСТ 2: Для загруженной модели")
if 'model_test' in locals():
    inference_time_loaded = measure_inference_time(
        model=model_test,
        test_loader=test_loader,
        device=device,
        num_batches=10
    )

# Способ 3: Сравнение CPU vs GPU
print("\nТЕСТ 3: Сравнение CPU и GPU")
if torch.cuda.is_available():
    # Тест на GPU
    gpu_time = measure_inference_time(model, test_loader, device, num_batches=10)

    # Тест на CPU
    cpu_device = torch.device('cpu')
    model_cpu = model.to(cpu_device)
    cpu_time = measure_inference_time(model_cpu, test_loader, cpu_device, num_batches=5)

    print(f"\nСравнение:")
    print(f"   GPU время: {gpu_time*1000:.2f} мс на отзыв")
    print(f"   CPU время: {cpu_time*1000:.2f} мс на отзыв")
    print(f"   GPU быстрее в {cpu_time/gpu_time:.1f} раз")

"""**Результаты на GPU:**
Среднее время обработки одного отзыва составляет 15-16 миллисекунды. Это позволяет обрабатывать около 66 отзывов в секунду, около 4000 отзывов в минуту или более 230 000 отзывов в час. Результаты стабильны с небольшим разбросом значений.

**Результаты на CPU:**
Для сравнения, на CPU обработка одного отзыва занимает около 758 миллисекунд, что в 50 раз медленнее. Производительность составляет всего 1.3 отзыва в секунду.

**Вывод:**
Модель полностью соответствует требованию задания о "достаточно коротком времени вывода для практического использования". Время 15.19 мс на отзыв позволяет использовать модель в реальных приложениях.
"""